# Generated by Django 5.1.3 on 2024-11-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_opinion',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_opinion',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_opinion',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_opinion',
            name='opinion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer_opinion',
            name='opinion_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer_opinion',
            name='opinion_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='functionsmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
